spring:
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    import: classpath:config/application-prod.yml
    activate:
      on-profile: prod